chore: e2e fixes (#1791)

diff --git a/.github/workflows/e2e-tests.yaml b/.github/workflows/e2e-tests.yaml
--- a/.github/workflows/e2e-tests.yaml
+++ b/.github/workflows/e2e-tests.yaml
@@ -1,5 +1,5 @@
 name: E2E tests
-run-name: E2E tests ${{ inputs.provider || 'azure' }}
+run-name: E2E tests ${{ inputs.provider }}
 
 # Required GitHub Repository Configuration:
 #
@@ -17,25 +17,41 @@ on:
         type: choice
         required: true
         options:
+          - ''
           - aws
           - gcp
           - azure
-        description: Choose the cloud provider for the shared instance
-        default: azure
-      feature_flags:
+        description: Cloud provider
+      tags:
         type: string
         required: false
-        description: 'Feature flag file: ff_edge.yaml (default, with backup) | ff_ga.yaml (GA only)'
-        default: ./pkg/feature/ff_edge.yaml
+        description: |
+          Godog tags (provider automatically appended)
+      feature_flags:
+        type: choice
+        required: true
+        options:
+          - ./pkg/feature/ff_edge.yaml
+          - ./pkg/feature/ff_ga.yaml
+        description: Feature flag file
+      debug:
+        type: boolean
+        description: Extra logs and prints
+        default: false
 jobs:
   test:
     runs-on: ubuntu-latest
     env:
       AWS_ROLE_NAME: CloudManagerRole
       AWS_PEERING_ROLE_NAME: CloudManagerPeeringRole
+      DEBUG:  ${{ inputs.debug && 'true' || '' }}
+      RUN_E2E_TESTS: 1
+      CONFIG_DIR: ${{ github.workspace }}/tmp
+      GHERKIN_REPORT: ${{ github.workspace }}/output.gherkin
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
+
       - name: Validate required configuration
         shell: bash
         run: |
@@ -51,14 +67,34 @@ jobs:
             exit 1
           fi
           echo "✅ All required configuration variables are set"
+
       - name: Set provider env var
         run: |
           PROVIDER=${{ inputs.provider }}
-          PROVIDER=${PROVIDER:-"azure"}
           echo "PROVIDER=$PROVIDER" >> $GITHUB_ENV
+
       - name: Break if provider is empty
         if: ${{ env.PROVIDER == '' }}
         run: echo "PROVIDER is missing or empty!" && exit 1
+
+      - name: Setup tags
+        run: |
+          TAGS="@$PROVIDER && ~@skip"
+          if [ -n "${{ inputs.tags }}" ]; then
+            TAGS="${{ inputs.tags }} && $TAGS"
+          fi
+          echo "Running tests with tag: $TAGS"
+          echo "TAGS=$TAGS" >> $GITHUB_ENV
+
+      - name: Inputs OK
+        run: |
+          echo "INPUTSOK='true'" >> $GITHUB_ENV
+          
+          echo "# Runtime info :information_source:" >> $GITHUB_STEP_SUMMARY
+          echo " * Provider: \\`$PROVIDER\\`" >> $GITHUB_STEP_SUMMARY
+          echo " * Tags: \\`$TAGS\\`" >> $GITHUB_STEP_SUMMARY
+          echo " * Debug: \\`$DEBUG\\`" >> $GITHUB_STEP_SUMMARY
+
       - name: Initialize E2E environment
         uses: ./.github/actions/e2e-init
         id: e2e-init
@@ -67,43 +103,103 @@ jobs:
           oidc_client_id: ${{ vars.OIDC_CLIENT_ID }}
           oidc_issuer_url: ${{ vars.OIDC_ISSUER_URL }}
           feature_flag_file: ${{ inputs.feature_flags || './pkg/feature/ff_edge.yaml' }}
+
       - name: Create shared instance
         env:
           KUBECONFIG: ./tmp/kubeconfig-kcp.yaml
         run: |
-          go run ./e2e/cmd instance create -a shared-$PROVIDER -p $PROVIDER -t 30m -w
+          go run ./e2e/cmd instance create -a shared-$PROVIDER -p $PROVIDER -t 30m -w -v
+
+      - name: Print Instance Details
+        env:
+          KUBECONFIG: ./tmp/kubeconfig-kcp.yaml
+        run: |
+          DETAILS=$(go run ./e2e/cmd instance show -a shared-$PROVIDER)
+          echo "$DETAILS"
+          
+          echo "# Instance Details :information_source:" >> $GITHUB_STEP_SUMMARY
+          echo "$DETAILS" | awk '{print "* " toupper(substr($0,1,1)) substr($0,2)}' >> $GITHUB_STEP_SUMMARY
+
       - name: Add module to shared instance
         env:
           KUBECONFIG: ${{ github.workspace }}/tmp/kubeconfig-kcp.yaml
         run: |
-          go run ./e2e/cmd instance modules add -m  cloud-manager -a shared-$PROVIDER
-          sleep 60
+          go run ./e2e/cmd instance modules add -m cloud-manager -a shared-$PROVIDER --wait --verbose --timeout 5m
+
       - name: run e2e tests
         env:
           KUBECONFIG: ${{ github.workspace }}/tmp/kubeconfig-kcp.yaml
         run: |
-          echo $KUBECONFIG
-          ls -la ./tmp
-          RUN_E2E_TESTS=1 PROJECTROOT=$GITHUB_WORKSPACE go test ./e2e/tests/skr/all/... -timeout 0 -v -godog.tags "@skr && @$PROVIDER"
+          if [ -n "$DEBUG" ]; then
+            echo "TAGS=$TAGS"
+            echo "KUBECONFIG=$KUBECONFIG"
+            echo "CONIFG_DIR=$CONFIG_DIR"
+            ls -la ./tmp
+            go run ./e2e/cmd config dump
+          fi
+          go test ./e2e/tests -timeout 0 -v -race -godog.tags "$TAGS" -godog.format "pretty,pretty:$GHERKIN_REPORT"
+
+      - name: Print Gherkin Report
+        if: always() && env.INPUTSOK != ''
+        run: |
+          if [ -f "$GHERKIN_REPORT" ]; then
+            echo
+            echo '# Features' >> $GITHUB_STEP_SUMMARY
+            echo '```gherkin' >> $GITHUB_STEP_SUMMARY
+            cat $GHERKIN_REPORT | sed 's/\x1b\[[0-9;]*[mGKH]//g' >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo
+          fi
+
+        # task "Cleaning extended API groups" failed: 1 error occurred:
+        #  * retry failed with context deadline exceeded, last error: remaining objects are still present:
+        # *v1.CustomResourceDefinition /cloudresources.cloud-resources.kyma-project.io
+        # *v1.CustomResourceDefinition /ipranges.cloud-resources.kyma-project.io
+        # *v1.CustomResourceDefinition /kymas.operator.kyma-project.io
+
+        # delete any leftover cloud-resources, but not CloudResources and not Kyma
       - name: Clean up orphaned SKR resources
-        if: always()
+        if: always() && env.INPUTSOK != ''
         env:
           KUBECONFIG: ${{ github.workspace }}/tmp/kubeconfig-kcp.yaml
         run: |
-          echo "Cleaning up orphaned cloud resources from SKR instance..."
-          echo "This runs after tests (pass or fail) while SIM and CM are still active"
-          go run ./e2e/cmd instance clean -a shared-$PROVIDER --verbose || {
-            echo "⚠️  Cleanup failed, but continuing with instance deletion..."
-          }
-          sleep 60
+          if [ -f "$KUBECONFIG" ]; then
+            go run ./e2e/cmd instance clean --alias shared-$PROVIDER --verbose --wait --force --timeout 30m
+          fi
+
+      - name: Remove CloudManager Module
+        if: always() && env.INPUTSOK != ''
+        env:
+          KUBECONFIG: ${{ github.workspace }}/tmp/kubeconfig-kcp.yaml
+        run: |
+          if [ -f "$KUBECONFIG" ]; then
+            go run ./e2e/cmd instance module remove --alias shared-$PROVIDER --module cloud-manager
+            sleep 10
+          fi
+
       - name: Delete shared instance
-        if: always()
+        if: always() && env.INPUTSOK != ''
         env:
           KUBECONFIG: ./tmp/kubeconfig-kcp.yaml
         run: |
-          go run ./e2e/cmd instance delete -a shared-$PROVIDER -t 60m -w
-          sleep 60
+          if [ -f "$KUBECONFIG" ]; then
+            go run ./e2e/cmd instance delete -a shared-$PROVIDER -t 60m -w -v
+            # give time to sim to pick-up
+            sleep 10
+          fi
+
+        # just in case it wasn't deleted gracefully - delete forcefully CloudResources and Kyma CR so Shoot can be deleted
+        # it may happen SKR instance does not exist, thus || true
+      - name: Clean up everything from SKR forcefully
+        if: always() && env.INPUTSOK != ''
+        env:
+          KUBECONFIG: ${{ github.workspace }}/tmp/kubeconfig-kcp.yaml
+        run: |
+          if [ -f "$KUBECONFIG" ]; then
+            go run ./e2e/cmd instance clean --alias shared-$PROVIDER --verbose --wait --all --force --timeout 1s || true
+          fi
+
       - name: Destroy E2E environment
-        if: always()
+        if: always() && env.INPUTSOK != ''
         uses: ./.github/actions/e2e-destroy
         id: e2e-destroy
